/* USER CODE BEGIN Header */
/*
 * STM32_ACU_wiring_test_cube_v1_0.c
 *
 * Target: STM32F401VETx
 * Toolchain: STM32CubeIDE, project generated by STM32CubeMX
 *
 * Replace Core/Src/main.c with this file.
 *
 * Proteus bench architecture in this version:
 *   - STM32F401VE is the ACU master
 *   - SensorHub ATmega emulates IMU, HighG_L/R and KP200_L/R
 *   - Actuator hub ATmega currently used only as a Squib output stage
 *
 * Design intent:
 *   - keep all buses software-driven on STM32 for Proteus robustness
 *   - keep the firmware as one-file scaffolding that already contains
 *     self-test, monitoring and ACU decision logic
 *   - leave room for later extraction into hal/drivers/algorithms modules
 */
/* USER CODE END Header */

#include "main.h"
#include "usart.h"
#include "gpio.h"

#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdint.h>
#include <math.h>

#define G_TO_MS2                     9.80665f

#define SENSOR_FLAG_IMU              (1U << 0)
#define SENSOR_FLAG_HIGHG_L          (1U << 1)
#define SENSOR_FLAG_HIGHG_R          (1U << 2)
#define SENSOR_FLAG_KP200_L          (1U << 3)
#define SENSOR_FLAG_KP200_R          (1U << 4)
#define SENSOR_FLAG_ALL              (SENSOR_FLAG_IMU | SENSOR_FLAG_HIGHG_L | SENSOR_FLAG_HIGHG_R | \
                                      SENSOR_FLAG_KP200_L | SENSOR_FLAG_KP200_R)

#define SENSOR_PROTO_READ_BIT        0x80U

#define IMU_WHO_AM_I_REG             0x0F
#define IMU_WHO_AM_I_VAL             0x6B
#define IMU_CTRL1_XL_REG             0x10
#define IMU_CTRL2_G_REG              0x11
#define IMU_STATUS_REG               0x1E
#define IMU_OUTX_L_G_REG             0x22
#define IMU_OUTX_L_A_REG             0x28

#define HIGHG_WHO_AM_I_REG           0x0F
#define HIGHG_WHO_AM_I_VAL           0x32
#define HIGHG_CTRL1_REG              0x20
#define HIGHG_STATUS_REG             0x27
#define HIGHG_OUT_X_L_REG            0x28

#define KP200_L_WHO_AM_I_VAL         0xA1
#define KP200_R_WHO_AM_I_VAL         0xA2
#define KP200_WHO_AM_I_REG           0x0F
#define KP200_STATUS_REG             0x10
#define KP200_PRESSURE_H_REG         0x11
#define KP200_PRESSURE_L_REG         0x12
#define KP200_CTRL_REG               0x20
#define KP200_FAULT_REG              0x21

#define EMU_STATUS_DRDY              0x01
#define EMU_STATUS_FAULT             0x80

#define SQUIB_MASK_FRONT             0x01
#define SQUIB_MASK_BELT              0x02
#define SQUIB_MASK_SIDE_L            0x04
#define SQUIB_MASK_SIDE_R            0x08
#define SQUIB_MASK_ROLLOVER          0x10

#define SQUIB_CMD_ALL_OFF            0x00
#define SQUIB_CMD_FRONT_RESTRAINTS   (SQUIB_MASK_FRONT | SQUIB_MASK_BELT)
#define SQUIB_CMD_SIDE_LEFT          (SQUIB_MASK_SIDE_L | SQUIB_MASK_ROLLOVER)
#define SQUIB_CMD_SIDE_RIGHT         (SQUIB_MASK_SIDE_R | SQUIB_MASK_ROLLOVER)
#define SQUIB_CMD_REAR_ONLY          SQUIB_MASK_BELT
#define SQUIB_CMD_ROLLOVER_ONLY      (SQUIB_MASK_SIDE_L | SQUIB_MASK_SIDE_R | SQUIB_MASK_ROLLOVER)
#define SQUIB_CMD_ALL_ON             0x1F

#define EDR_WHO_AM_I                 0xE4

#define EDR_REG_WHO_AM_I             0x0F
#define EDR_REG_STATUS               0x10
#define EDR_REG_STAGE                0x11
#define EDR_REG_SCENARIO_INPUTS      0x12
#define EDR_REG_SENSOR_FLAGS         0x13
#define EDR_REG_LAST_SQUIB_CMD       0x14
#define EDR_REG_SQUIB_OUTPUT_MASK    0x15
#define EDR_REG_HOST_EVENT_ID        0x16
#define EDR_REG_HOST_FLAGS           0x17
#define EDR_REG_HOST_DATA0           0x18
#define EDR_REG_HOST_DATA1           0x19
#define EDR_REG_TRANSACTION_H        0x1A
#define EDR_REG_TRANSACTION_L        0x1B
#define EDR_REG_CTRL                 0x20
#define EDR_REG_FAULT                0x21

#define EDR_STATUS_INIT_DONE         (1U << 0)
#define EDR_STATUS_READ_SEEN         (1U << 1)
#define EDR_STATUS_WRITE_SEEN        (1U << 2)
#define EDR_STATUS_SQUIB_ACTIVITY    (1U << 3)
#define EDR_STATUS_LOG_VALID         (1U << 4)
#define EDR_STATUS_FAULT             (1U << 5)

#define EDR_CTRL_CLEAR_STATUS        (1U << 0)
#define EDR_CTRL_CLEAR_LOG           (1U << 1)

#define EDR_STAGE_BOOT               0x01
#define EDR_STAGE_SELFTEST           0x02
#define EDR_STAGE_READY              0x03
#define EDR_STAGE_MONITOR            0x04
#define EDR_STAGE_VISUAL             0x05
#define EDR_STAGE_DEPLOYED           0x06
#define EDR_STAGE_LOCKED             0x07
#define EDR_STAGE_FAULT              0x08

#define EDR_HOST_EVENT_BOOT          0x10
#define EDR_HOST_EVENT_SELFTEST_OK   0x11
#define EDR_HOST_EVENT_VISUAL        0x20
#define EDR_HOST_EVENT_FRONT         0x30
#define EDR_HOST_EVENT_SIDE_LEFT     0x31
#define EDR_HOST_EVENT_SIDE_RIGHT    0x32
#define EDR_HOST_EVENT_REAR          0x33
#define EDR_HOST_EVENT_ROLLOVER      0x34
#define EDR_HOST_EVENT_FAULT         0xE0

#define EDR_HOST_FLAG_SENSOR_OK      (1U << 0)
#define EDR_HOST_FLAG_DEPLOYED       (1U << 1)
#define EDR_HOST_FLAG_VISUAL_DONE    (1U << 2)
#define EDR_HOST_FLAG_FAULT          (1U << 3)

#define INPUT_SCENARIO_MASK          0x07U
#define INPUT_START_BIT              (1U << 3)
#define INPUT_RESET_BIT              (1U << 4)
#define INPUT_FAULT_BIT              (1U << 5)

#define SCENARIO_IDLE                0x00
#define SCENARIO_FRONT               0x01
#define SCENARIO_SIDE_LEFT           0x02
#define SCENARIO_SIDE_RIGHT          0x03
#define SCENARIO_REAR                0x04
#define SCENARIO_ROLLOVER            0x05
#define SCENARIO_MISUSE              0x06
#define SCENARIO_VISUAL              0x07

#define TICK_2KHZ_HZ                 2000U
#define TICK_DT_S                    0.0005f
#define DEPLOY_HOLD_TICKS            1200U
#define RAD_TO_DEG                   57.2957795f

#define FRONT_CONFIRM_TICKS          2U
#define SIDE_CONFIRM_TICKS           1U
#define REAR_CONFIRM_TICKS           3U
#define ROLLOVER_CONFIRM_TICKS       2U

#define FRONT_IMU_TH_MS2             (3.5f * G_TO_MS2)
#define FRONT_HIGHG_TH_MS2           (5.0f * G_TO_MS2)
#define SIDE_IMU_TH_MS2              (10.0f * G_TO_MS2)
#define SIDE_HIGHG_TH_MS2            (15.0f * G_TO_MS2)
#define SIDE_PPS_TH_KPA              5.0f
#define REAR_IMU_TH_MS2              (3.0f * G_TO_MS2)
#define REAR_HIGHG_TH_MS2            (3.0f * G_TO_MS2)
#define ROLLOVER_GX_TH_DPS           90.0f
#define ROLLOVER_AY_TH_MS2           (2.0f * G_TO_MS2)
#define ROLLOVER_PHI_TH_DEG          45.0f

#define FRONT_DV_THRESHOLD_MS        4.0f
#define SIDE_DV_THRESHOLD_MS         0.80f
#define REAR_DV_THRESHOLD_MS         2.20f
#define ROLLOVER_SAFING_DV_MS        2.0f

#define FRONT_ONSET_TH_MS2           (0.5f * G_TO_MS2)
#define SIDE_ONSET_TH_MS2            (0.5f * G_TO_MS2)
#define REAR_ONSET_TH_MS2            (0.5f * G_TO_MS2)
#define ROLLOVER_ONSET_DPS           5.0f

#define PLAUSIBILITY_FRONT_MIN_TICKS     10U
#define PLAUSIBILITY_FRONT_MAX_TICKS     400U
#define PLAUSIBILITY_SIDE_MIN_TICKS      4U
#define PLAUSIBILITY_SIDE_MAX_TICKS      60U
#define PLAUSIBILITY_REAR_MIN_TICKS      40U
#define PLAUSIBILITY_REAR_MAX_TICKS      240U
#define PLAUSIBILITY_ROLLOVER_MIN_TICKS  300U
#define PLAUSIBILITY_ROLLOVER_MAX_TICKS  4000U

/*
 * The Proteus scaffold uses scaled synthetic pulses, so the algorithm
 * structure follows ACU_LADA while several calibration constants below are
 * tuned to the current emulated profiles rather than a production vehicle.
 */
#define FRONT_RED_B_MS2              (3.5f * G_TO_MS2)
#define FRONT_RED_S0_M               0.0038f
#define FRONT_RED_E0                 0.0f
#define FRONT_RED_SLOPE_M            (-80.0f)

#define SIDE_RED_ENERGY_THRESHOLD    40.0f

#define JERK_WINDOW_TICKS            20U
#define JERK_FRONT_MIN               50000.0f
#define JERK_FRONT_MAX               5000000.0f
#define JERK_SIDE_MIN                120000.0f
#define JERK_SIDE_MAX                12000000.0f

#define SAFING_WINDOW_TICKS          60U
#define SAFING_REARM_TICKS           1000U
#define SAFING_IDLE_AX_MS2           (0.5f * G_TO_MS2)
#define SAFING_IDLE_AY_MS2           (0.5f * G_TO_MS2)

#define OSC_WINDOW_TICKS             50U
#define OSC_SIGN_CHANGE_LIMIT        1U

#define ROLLOVER_ARMING_DPS          15.0f
#define ROLLOVER_PHI_CRITICAL_DEG    54.5f
#define ROLLOVER_HIGHG_FREEZE_BAND   (2.0f * G_TO_MS2)
#define ROLLOVER_FILTER_ALPHA        0.98f
#define ROLLOVER_MONOTONIC_TICKS     400U

#define IMU_ACCEL_G_PER_LSB          0.000488f
#define IMU_GYRO_DPS_PER_LSB         0.140f
#define HIGHG_G_PER_LSB              0.01f

#define EDR_CS_GPIO_Port             GPIOA
#define EDR_CS_Pin                   GPIO_PIN_15

typedef struct {
    GPIO_TypeDef *sck_port;
    uint16_t sck_pin;
    GPIO_TypeDef *miso_port;
    uint16_t miso_pin;
    GPIO_TypeDef *mosi_port;
    uint16_t mosi_pin;
} soft_spi_bus_t;

struct sensor_desc {
    const char *name;
    GPIO_TypeDef *port;
    uint16_t pin;
    uint8_t who_expected;
};

typedef struct {
    float ax;
    float ay;
    float az;
    float gx;
    float gy;
    float gz;
    uint8_t valid;
} imu_data_t;

typedef struct {
    float ax;
    float ay;
    float az;
    uint8_t valid;
} highg_data_t;

typedef struct {
    float dp_kpa;
    uint8_t valid;
    uint8_t fault;
} kp200_data_t;

typedef struct {
    imu_data_t imu;
    highg_data_t highg_l;
    highg_data_t highg_r;
    kp200_data_t kp200_l;
    kp200_data_t kp200_r;
    uint8_t flags;
} sensor_snapshot_t;

typedef enum {
    ACU_STATE_BOOT = 0,
    ACU_STATE_SELFTEST,
    ACU_STATE_READY,
    ACU_STATE_MONITOR,
    ACU_STATE_DEPLOYED,
    ACU_STATE_LOCKED,
    ACU_STATE_FAULT
} acu_state_t;

typedef enum {
    CRASH_EVENT_NONE = 0,
    CRASH_EVENT_FRONT,
    CRASH_EVENT_SIDE_LEFT,
    CRASH_EVENT_SIDE_RIGHT,
    CRASH_EVENT_REAR,
    CRASH_EVENT_ROLLOVER,
    CRASH_EVENT_VISUAL
} crash_event_t;

typedef struct {
    float v_ms;
    float s_m;
    float e_res;
    float last_a_ms2;
    uint8_t started;
    uint8_t should_deploy;
} front_red_state_t;

typedef struct {
    float dv_ms;
    float energy;
    uint8_t should_deploy;
} side_red_state_t;

typedef struct {
    float dv_ms;
    uint8_t detected;
} rear_state_t;

typedef struct {
    float dv_ms;
    uint16_t window_ticks;
    uint16_t idle_ticks;
    uint8_t armed;
} safing_gate_t;

typedef struct {
    float energy;
    float last_a;
    uint16_t samples;
    uint8_t initialized;
    uint8_t is_crash;
} jerk_gate_t;

typedef struct {
    int8_t last_sign;
    uint8_t sign_changes;
    uint16_t samples;
    uint8_t is_oscillation;
} osc_gate_t;

typedef struct {
    uint16_t front_duration_ticks;
    uint16_t side_left_duration_ticks;
    uint16_t side_right_duration_ticks;
    uint16_t rear_duration_ticks;
    uint16_t rollover_duration_ticks;
    uint8_t front_count;
    uint8_t side_left_count;
    uint8_t side_right_count;
    uint8_t rear_count;
    uint8_t rollover_count;
    uint8_t front_sign_changes;
    uint8_t side_left_sign_changes;
    uint8_t side_right_sign_changes;
    uint8_t rear_sign_changes;
    uint8_t gyro_sign_changes;
    front_red_state_t front_red;
    side_red_state_t side_left_red;
    side_red_state_t side_right_red;
    rear_state_t rear_logic;
    safing_gate_t safing_front;
    safing_gate_t safing_side_left;
    safing_gate_t safing_side_right;
    safing_gate_t safing_rear;
    safing_gate_t safing_rollover;
    jerk_gate_t jerk_front;
    jerk_gate_t jerk_side_left;
    jerk_gate_t jerk_side_right;
    osc_gate_t osc_front;
    osc_gate_t osc_side_left;
    osc_gate_t osc_side_right;
    osc_gate_t osc_rear;
    osc_gate_t osc_gyro;
    float roll_angle_deg;
    float prev_roll_angle_deg;
    float rollover_phase_metric;
    uint16_t rollover_monotonic_ticks;
} decision_state_t;

void SystemClock_Config(void);
void Error_Handler(void);

static void uart_puts(const char *s);
static void uart_printf(const char *fmt, ...);
static float f_abs(float value);
static int8_t sign_with_deadband(float value, float deadband);
static int16_t le16_to_s16(const uint8_t *buf);
static int16_t be16_to_s16(const uint8_t *buf);
static void format_ticks_ms(uint32_t ticks, char *buffer, uint32_t buffer_size);

static void led_all_off(void);
static void led_set_ready_state(void);
static void led_set_monitor_state(void);
static void led_set_deployed_state(void);
static void led_set_locked_state(void);
static void led_set_fault_state(void);

static uint8_t read_scenario_inputs_stm32(void);
static const char *scenario_name(uint8_t scenario);
static uint8_t scenario_activity_detected(uint8_t scenario, const sensor_snapshot_t *snapshot);

static void soft_spi_delay_cycles(uint32_t cycles);
static void soft_spi_edge_delay(void);
static void soft_spi_select_delay(void);
static void soft_spi_interbyte_delay(void);
static uint8_t soft_spi_transfer_byte(const soft_spi_bus_t *bus, uint8_t tx);

static void sensorhub_gpio_bus_init(void);
static void sensorhub_release_all_cs(void);
static void sensorhub_begin_transaction(GPIO_TypeDef *cs_port, uint16_t cs_pin);
static void sensorhub_end_transaction(GPIO_TypeDef *cs_port, uint16_t cs_pin);
static uint8_t sensorhub_read_regs(const struct sensor_desc *sensor, uint8_t addr, uint8_t *buf, uint8_t len);
static uint8_t sensorhub_read_reg_u8(const struct sensor_desc *sensor, uint8_t addr, uint8_t *value);
static uint8_t sensorhub_read_reg_u8_retry(const struct sensor_desc *sensor, uint8_t addr, uint8_t *value, uint8_t attempts);
static void sensorhub_write_reg(const struct sensor_desc *sensor, uint8_t addr, uint8_t value);
static void sensorhub_prime_link(void);
static uint8_t sensorhub_selftest_and_configure(void);
static uint8_t imu_read(imu_data_t *data);
static uint8_t highg_read(const struct sensor_desc *sensor, highg_data_t *data);
static uint8_t kp200_read(const struct sensor_desc *sensor, kp200_data_t *data);
static uint8_t sample_all_sensors(sensor_snapshot_t *snapshot);

static void actuator_edr_gpio_bus_init(void);
static void actuator_edr_release_all_cs(void);
static void actuator_edr_begin_squib(void);
static void actuator_edr_begin_edr(void);
static void actuator_edr_end_transaction(GPIO_TypeDef *cs_port, uint16_t cs_pin);
static void squib_send_command(uint8_t cmd);
static void test_squib_visual(void);

static void edr_write_reg(uint8_t addr, uint8_t value);
static uint8_t edr_read_reg(uint8_t addr);
static uint8_t edr_test_link(void);
static void edr_clear_log(void);
static void edr_log_boot(uint8_t scenario_inputs);
static void edr_log_selftest_ok(void);
static void edr_log_ready(void);
static void edr_log_monitor(uint8_t scenario_inputs, uint8_t sensor_flags);
static void edr_log_deploy(crash_event_t event, uint8_t squib_mask, uint8_t scenario_inputs, uint8_t sensor_flags);
static void edr_log_visual_complete(void);
static void edr_log_fault(uint8_t scenario_inputs, uint8_t sensor_flags);
static void edr_dump_summary(void);

static void tim3_init_2khz(void);
static uint8_t cross_validate_frontal(const sensor_snapshot_t *snapshot);
static uint8_t cross_validate_side_left(const sensor_snapshot_t *snapshot);
static uint8_t cross_validate_side_right(const sensor_snapshot_t *snapshot);
static uint8_t cross_validate_rear(const sensor_snapshot_t *snapshot);
static uint8_t cross_validate_rollover(const sensor_snapshot_t *snapshot);
static void update_safing_gate(safing_gate_t *gate, float a_independent, float threshold_ms, float dt_s, float idle_threshold_ms2);
static void update_jerk_gate(jerk_gate_t *gate, float a_current, float dt_s, float energy_min, float energy_max, uint8_t active);
static void update_oscillation_gate(osc_gate_t *gate, int8_t sign, uint8_t active);
static void print_decision_metrics(crash_event_t event, const decision_state_t *state);
static void decision_reset(decision_state_t *state);
static crash_event_t evaluate_event(const sensor_snapshot_t *snapshot, decision_state_t *state, float dt_s);
static uint8_t event_to_squib_mask(crash_event_t event);
static uint8_t event_to_edr_host_id(crash_event_t event);
static const char *event_name(crash_event_t event);
static uint8_t perform_startup_selftest(uint8_t scenario_inputs);
static void enter_fault_state(uint8_t scenario_inputs, uint8_t sensor_flags, const char *reason);

static const soft_spi_bus_t g_sensorhub_bus = {
    GPIOA, GPIO_PIN_5,
    GPIOA, GPIO_PIN_6,
    GPIOA, GPIO_PIN_7
};

static const soft_spi_bus_t g_actuator_edr_bus = {
    GPIOB, GPIO_PIN_13,
    GPIOB, GPIO_PIN_14,
    GPIOB, GPIO_PIN_15
};

static const struct sensor_desc g_sensor_imu = {
    "IMU", CS_IMU_GPIO_Port, CS_IMU_Pin, IMU_WHO_AM_I_VAL
};

static const struct sensor_desc g_sensor_highg_l = {
    "HIGHG_L", CS_HIGHG_L_GPIO_Port, CS_HIGHG_L_Pin, HIGHG_WHO_AM_I_VAL
};

static const struct sensor_desc g_sensor_highg_r = {
    "HIGHG_R", CS_HIGHG_R_GPIO_Port, CS_HIGHG_R_Pin, HIGHG_WHO_AM_I_VAL
};

static const struct sensor_desc g_sensor_kp200_l = {
    "KP200_L", CS_PPS_L_GPIO_Port, CS_PPS_L_Pin, KP200_L_WHO_AM_I_VAL
};

static const struct sensor_desc g_sensor_kp200_r = {
    "KP200_R", CS_PPS_R_GPIO_Port, CS_PPS_R_Pin, KP200_R_WHO_AM_I_VAL
};

static acu_state_t g_state = ACU_STATE_BOOT;
static decision_state_t g_decision = {0};
static crash_event_t g_last_event = CRASH_EVENT_NONE;
static uint8_t g_last_squib_cmd = SQUIB_CMD_ALL_OFF;
static uint32_t g_deploy_timestamp = 0U;
static volatile uint32_t g_tick_2khz_counter = 0U;
static volatile uint32_t g_tick_2khz_missed = 0U;
static uint32_t g_processed_tick_2khz = 0U;
static uint32_t g_monitor_start_tick_2khz = 0U;
static uint32_t g_impact_onset_tick_2khz = 0U;
static uint8_t g_impact_seen = 0U;
static uint8_t g_monitor_scenario = SCENARIO_IDLE;

int main(void)
{
    uint8_t inputs;
    uint8_t prev_inputs = 0U;
    uint32_t last_blink_tick = 0U;

    HAL_Init();
    SystemClock_Config();

    MX_GPIO_Init();
    MX_USART2_UART_Init();
    tim3_init_2khz();

    sensorhub_gpio_bus_init();
    actuator_edr_gpio_bus_init();
    sensorhub_release_all_cs();
    actuator_edr_release_all_cs();
    squib_send_command(SQUIB_CMD_ALL_OFF);

    uart_puts("\r\n");
    uart_puts("========================================\r\n");
    uart_puts("ACU_LADA Proteus scaffold v1.0\r\n");
    uart_puts("SensorHub: IMU + HighG + KP200 virtual register model\r\n");
    uart_puts("Actuator: squib outputs only, EDR path removed from this bench stage\r\n");
    uart_puts("STM32 transport: software SPI on both buses, HSI system clock\r\n");
    uart_puts("Scenarios: 0 idle, 1 front, 2 side_L, 3 side_R, 4 rear, 5 rollover, 6 misuse, 7 visual\r\n");
    uart_puts("========================================\r\n");

    inputs = read_scenario_inputs_stm32();
    (void)perform_startup_selftest(inputs);
    prev_inputs = inputs;
    g_processed_tick_2khz = g_tick_2khz_counter;
    last_blink_tick = HAL_GetTick();

    while (1) {
        uint32_t current_tick_2khz = g_tick_2khz_counter;
        uint32_t now = HAL_GetTick();
        uint8_t start_edge;
        uint8_t reset_edge;
        uint8_t scenario;

        inputs = read_scenario_inputs_stm32();
        scenario = (uint8_t)(inputs & INPUT_SCENARIO_MASK);
        start_edge = ((inputs & INPUT_START_BIT) != 0U) && ((prev_inputs & INPUT_START_BIT) == 0U);
        reset_edge = ((inputs & INPUT_RESET_BIT) != 0U) && ((prev_inputs & INPUT_RESET_BIT) == 0U);

        if ((now - last_blink_tick) >= 500U) {
            HAL_GPIO_TogglePin(LED_TICK_GPIO_Port, LED_TICK_Pin);
            last_blink_tick = now;
        }

        if (reset_edge) {
            uart_puts("[RESET] Restarting ACU self-test...\r\n");
            (void)perform_startup_selftest(inputs);
            prev_inputs = inputs;
            g_processed_tick_2khz = g_tick_2khz_counter;
            continue;
        }

        if ((inputs & INPUT_FAULT_BIT) != 0U && g_state != ACU_STATE_FAULT) {
            enter_fault_state(inputs, 0x00, "TEST_FAULT input active");
        }

        switch (g_state) {
        case ACU_STATE_READY:
            if (start_edge) {
                if (scenario == SCENARIO_VISUAL) {
                    uart_puts("[VISUAL] Running actuator visual sequence...\r\n");
                    test_squib_visual();
                    g_last_event = CRASH_EVENT_VISUAL;
                    g_last_squib_cmd = SQUIB_CMD_ALL_OFF;
                    g_state = ACU_STATE_LOCKED;
                    led_set_locked_state();
                    uart_puts("[VISUAL] Sequence complete. Press RESET for a new run.\r\n");
                } else {
                    decision_reset(&g_decision);
                    g_monitor_scenario = scenario;
                    g_monitor_start_tick_2khz = g_tick_2khz_counter;
                    g_processed_tick_2khz = g_monitor_start_tick_2khz;
                    g_impact_onset_tick_2khz = 0U;
                    g_impact_seen = 0U;
                    g_state = ACU_STATE_MONITOR;
                    led_set_monitor_state();
                    uart_printf("[MONITOR] Scenario %u (%s), sampling at 2 kHz\r\n",
                                scenario, scenario_name(scenario));
                }
            }
            break;

        case ACU_STATE_MONITOR:
            if ((inputs & INPUT_START_BIT) == 0U) {
                g_state = ACU_STATE_READY;
                decision_reset(&g_decision);
                led_set_ready_state();
                uart_puts("[MONITOR] Start released. Back to READY.\r\n");
                break;
            }

            if (current_tick_2khz != g_processed_tick_2khz) {
                uint32_t diff = current_tick_2khz - g_processed_tick_2khz;

                if (diff > 1U) {
                    g_tick_2khz_missed += (diff - 1U);
                }

                while ((g_processed_tick_2khz != current_tick_2khz) && (g_state == ACU_STATE_MONITOR)) {
                    sensor_snapshot_t snapshot;
                    crash_event_t event;
                    uint8_t squib_mask;

                    g_processed_tick_2khz++;

                    if (!sample_all_sensors(&snapshot)) {
                        enter_fault_state(inputs, 0x00, "Sensor read transaction failed");
                        break;
                    }

                    if (snapshot.flags != SENSOR_FLAG_ALL) {
                        enter_fault_state(inputs, snapshot.flags, "Sensor validity check failed");
                        break;
                    }

                    if (!g_impact_seen && scenario_activity_detected(g_monitor_scenario, &snapshot)) {
                        char onset_buf[24];
                        g_impact_seen = 1U;
                        g_impact_onset_tick_2khz = g_processed_tick_2khz;
                        format_ticks_ms(g_impact_onset_tick_2khz - g_monitor_start_tick_2khz,
                                        onset_buf, sizeof(onset_buf));
                        uart_printf("[IMPACT] onset at +%s ms from START\r\n", onset_buf);
                    }

                    event = evaluate_event(&snapshot, &g_decision, TICK_DT_S);
                    if (event != CRASH_EVENT_NONE) {
                        char start_buf[24];
                        char onset_buf[24];

                        squib_mask = event_to_squib_mask(event);
                        squib_send_command(squib_mask);
                        g_last_squib_cmd = squib_mask;
                        g_last_event = event;
                        g_deploy_timestamp = g_processed_tick_2khz;
                        g_state = ACU_STATE_DEPLOYED;
                        led_set_deployed_state();

                        format_ticks_ms(g_deploy_timestamp - g_monitor_start_tick_2khz,
                                        start_buf, sizeof(start_buf));
                        if (g_impact_seen) {
                            format_ticks_ms(g_deploy_timestamp - g_impact_onset_tick_2khz,
                                            onset_buf, sizeof(onset_buf));
                        } else {
                            strcpy(onset_buf, "n/a");
                        }

                        uart_printf("[DEPLOY] %s -> squib mask 0x%02X, t_start=%s ms, t_impact=%s ms\r\n",
                                    event_name(event), squib_mask, start_buf, onset_buf);
                        print_decision_metrics(event, &g_decision);
                    }
                }
            }
            break;

        case ACU_STATE_DEPLOYED:
            if ((current_tick_2khz - g_deploy_timestamp) >= DEPLOY_HOLD_TICKS) {
                g_state = ACU_STATE_LOCKED;
                led_set_locked_state();
                uart_puts("[LOCKED] Outputs latched. Press RESET for next run.\r\n");
            }
            break;

        case ACU_STATE_LOCKED:
            /* Latched until external reset input. */
            break;

        case ACU_STATE_FAULT:
            /* Fault remains latched until external reset input. */
            break;

        case ACU_STATE_BOOT:
        case ACU_STATE_SELFTEST:
        default:
            break;
        }

        prev_inputs = inputs;
        HAL_Delay(2);
    }
}

static void uart_puts(const char *s)
{
    HAL_UART_Transmit(&huart2, (uint8_t *)s, (uint16_t)strlen(s), HAL_MAX_DELAY);
}

static void uart_printf(const char *fmt, ...)
{
    char buffer[224];
    va_list args;

    va_start(args, fmt);
    vsnprintf(buffer, sizeof(buffer), fmt, args);
    va_end(args);

    uart_puts(buffer);
}

static float f_abs(float value)
{
    return (value < 0.0f) ? -value : value;
}

static int8_t sign_with_deadband(float value, float deadband)
{
    if (value > deadband) {
        return 1;
    }
    if (value < -deadband) {
        return -1;
    }
    return 0;
}

static int16_t le16_to_s16(const uint8_t *buf)
{
    return (int16_t)((uint16_t)buf[0] | ((uint16_t)buf[1] << 8));
}

static int16_t be16_to_s16(const uint8_t *buf)
{
    return (int16_t)(((uint16_t)buf[0] << 8) | (uint16_t)buf[1]);
}

static void format_ticks_ms(uint32_t ticks, char *buffer, uint32_t buffer_size)
{
    snprintf(buffer, buffer_size, "%lu.%01lu",
             (unsigned long)(ticks / 2U),
             (unsigned long)((ticks & 1U) ? 5U : 0U));
}

static void led_all_off(void)
{
    HAL_GPIO_WritePin(GPIOD,
                      LED_READY_Pin | LED_ARMED_Pin | LED_CRASH_Pin | LED_LOCKED_Pin |
                      LED_SENSOR_OK_Pin | LED_EDR_Pin | LED_TICK_Pin | LED_FAULT_Pin,
                      GPIO_PIN_RESET);
}

static void led_set_ready_state(void)
{
    led_all_off();
    HAL_GPIO_WritePin(LED_READY_GPIO_Port, LED_READY_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(LED_SENSOR_OK_GPIO_Port, LED_SENSOR_OK_Pin, GPIO_PIN_SET);
}

static void led_set_monitor_state(void)
{
    led_set_ready_state();
    HAL_GPIO_WritePin(LED_ARMED_GPIO_Port, LED_ARMED_Pin, GPIO_PIN_SET);
}

static void led_set_deployed_state(void)
{
    led_set_monitor_state();
    HAL_GPIO_WritePin(LED_CRASH_GPIO_Port, LED_CRASH_Pin, GPIO_PIN_SET);
}

static void led_set_locked_state(void)
{
    led_set_ready_state();
    HAL_GPIO_WritePin(LED_LOCKED_GPIO_Port, LED_LOCKED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(LED_CRASH_GPIO_Port, LED_CRASH_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(LED_ARMED_GPIO_Port, LED_ARMED_Pin, GPIO_PIN_RESET);
}

static void led_set_fault_state(void)
{
    led_all_off();
    HAL_GPIO_WritePin(LED_FAULT_GPIO_Port, LED_FAULT_Pin, GPIO_PIN_SET);
}

static uint8_t read_scenario_inputs_stm32(void)
{
    uint8_t value = 0;

    if (HAL_GPIO_ReadPin(TEST0_GPIO_Port, TEST0_Pin) == GPIO_PIN_SET) value |= (1U << 0);
    if (HAL_GPIO_ReadPin(TEST1_GPIO_Port, TEST1_Pin) == GPIO_PIN_SET) value |= (1U << 1);
    if (HAL_GPIO_ReadPin(TEST2_GPIO_Port, TEST2_Pin) == GPIO_PIN_SET) value |= (1U << 2);
    if (HAL_GPIO_ReadPin(TEST_START_GPIO_Port, TEST_START_Pin) == GPIO_PIN_SET) value |= (1U << 3);
    if (HAL_GPIO_ReadPin(TEST_RESET_GPIO_Port, TEST_RESET_Pin) == GPIO_PIN_SET) value |= (1U << 4);
    if (HAL_GPIO_ReadPin(TEST_FAULT_GPIO_Port, TEST_FAULT_Pin) == GPIO_PIN_SET) value |= (1U << 5);

    return value;
}

static const char *scenario_name(uint8_t scenario)
{
    switch (scenario & INPUT_SCENARIO_MASK) {
    case SCENARIO_IDLE: return "idle";
    case SCENARIO_FRONT: return "front";
    case SCENARIO_SIDE_LEFT: return "side_left";
    case SCENARIO_SIDE_RIGHT: return "side_right";
    case SCENARIO_REAR: return "rear";
    case SCENARIO_ROLLOVER: return "rollover";
    case SCENARIO_MISUSE: return "misuse";
    case SCENARIO_VISUAL: return "visual";
    default: return "unknown";
    }
}

static uint8_t scenario_activity_detected(uint8_t scenario, const sensor_snapshot_t *snapshot)
{
    switch (scenario & INPUT_SCENARIO_MASK) {
    case SCENARIO_FRONT:
        return snapshot->imu.ax <= -FRONT_ONSET_TH_MS2;
    case SCENARIO_SIDE_LEFT:
        return (snapshot->imu.ay >= SIDE_ONSET_TH_MS2) || (snapshot->kp200_l.dp_kpa > 0.5f);
    case SCENARIO_SIDE_RIGHT:
        return (snapshot->imu.ay <= -SIDE_ONSET_TH_MS2) || (snapshot->kp200_r.dp_kpa > 0.5f);
    case SCENARIO_REAR:
        return snapshot->imu.ax >= REAR_ONSET_TH_MS2;
    case SCENARIO_ROLLOVER:
        return f_abs(snapshot->imu.gx) >= ROLLOVER_ONSET_DPS;
    case SCENARIO_MISUSE:
        return (f_abs(snapshot->imu.ax) >= FRONT_ONSET_TH_MS2) ||
               (f_abs(snapshot->imu.ay) >= SIDE_ONSET_TH_MS2) ||
               (f_abs(snapshot->imu.gx) >= ROLLOVER_ONSET_DPS);
    default:
        return 0U;
    }
}

static void soft_spi_delay_cycles(uint32_t cycles)
{
    volatile uint32_t i;

    for (i = 0; i < cycles; i++) {
        __NOP();
    }
}

static void soft_spi_edge_delay(void)
{
    soft_spi_delay_cycles(60U);
}

static void soft_spi_select_delay(void)
{
    soft_spi_delay_cycles(400U);
}

static void soft_spi_interbyte_delay(void)
{
    soft_spi_delay_cycles(2400U);
}

static uint8_t soft_spi_transfer_byte(const soft_spi_bus_t *bus, uint8_t tx)
{
    uint8_t rx = 0;
    uint8_t bit;

    for (bit = 0; bit < 8U; bit++) {
        HAL_GPIO_WritePin(bus->mosi_port, bus->mosi_pin,
                          (tx & 0x80U) ? GPIO_PIN_SET : GPIO_PIN_RESET);
        soft_spi_edge_delay();

        HAL_GPIO_WritePin(bus->sck_port, bus->sck_pin, GPIO_PIN_SET);
        soft_spi_edge_delay();

        rx <<= 1;
        if (HAL_GPIO_ReadPin(bus->miso_port, bus->miso_pin) == GPIO_PIN_SET) {
            rx |= 0x01U;
        }

        HAL_GPIO_WritePin(bus->sck_port, bus->sck_pin, GPIO_PIN_RESET);
        tx <<= 1;
        soft_spi_edge_delay();
    }

    HAL_GPIO_WritePin(bus->mosi_port, bus->mosi_pin, GPIO_PIN_RESET);
    return rx;
}

static void sensorhub_gpio_bus_init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    __HAL_RCC_GPIOA_CLK_ENABLE();

    GPIO_InitStruct.Pin = GPIO_PIN_5 | GPIO_PIN_7;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_6;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5 | GPIO_PIN_7, GPIO_PIN_RESET);
}

static void sensorhub_release_all_cs(void)
{
    HAL_GPIO_WritePin(CS_IMU_GPIO_Port, CS_IMU_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(CS_HIGHG_L_GPIO_Port, CS_HIGHG_L_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(CS_HIGHG_R_GPIO_Port, CS_HIGHG_R_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(CS_PPS_L_GPIO_Port, CS_PPS_L_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(CS_PPS_R_GPIO_Port, CS_PPS_R_Pin, GPIO_PIN_SET);
}

static void sensorhub_begin_transaction(GPIO_TypeDef *cs_port, uint16_t cs_pin)
{
    sensorhub_release_all_cs();
    soft_spi_select_delay();
    HAL_GPIO_WritePin(cs_port, cs_pin, GPIO_PIN_RESET);
    soft_spi_select_delay();
}

static void sensorhub_end_transaction(GPIO_TypeDef *cs_port, uint16_t cs_pin)
{
    soft_spi_select_delay();
    HAL_GPIO_WritePin(cs_port, cs_pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(g_sensorhub_bus.sck_port, g_sensorhub_bus.sck_pin, GPIO_PIN_RESET);
    soft_spi_select_delay();
}

static uint8_t sensorhub_read_regs(const struct sensor_desc *sensor, uint8_t addr, uint8_t *buf, uint8_t len)
{
    uint8_t i;

    sensorhub_begin_transaction(sensor->port, sensor->pin);
    (void)soft_spi_transfer_byte(&g_sensorhub_bus, (uint8_t)(SENSOR_PROTO_READ_BIT | addr));
    soft_spi_interbyte_delay();
    for (i = 0; i < len; i++) {
        buf[i] = soft_spi_transfer_byte(&g_sensorhub_bus, 0x00);
    }
    sensorhub_end_transaction(sensor->port, sensor->pin);

    return 1U;
}

static uint8_t sensorhub_read_reg_u8(const struct sensor_desc *sensor, uint8_t addr, uint8_t *value)
{
    return sensorhub_read_regs(sensor, addr, value, 1U);
}

static uint8_t sensorhub_read_reg_u8_retry(const struct sensor_desc *sensor, uint8_t addr, uint8_t *value, uint8_t attempts)
{
    uint8_t i;

    for (i = 0; i < attempts; i++) {
        if (sensorhub_read_reg_u8(sensor, addr, value)) {
            if (*value == sensor->who_expected) {
                return 1U;
            }
        }
        HAL_Delay(1);
    }

    return sensorhub_read_reg_u8(sensor, addr, value);
}

static void sensorhub_write_reg(const struct sensor_desc *sensor, uint8_t addr, uint8_t value)
{
    sensorhub_begin_transaction(sensor->port, sensor->pin);
    (void)soft_spi_transfer_byte(&g_sensorhub_bus, (uint8_t)(addr & 0x7FU));
    soft_spi_interbyte_delay();
    (void)soft_spi_transfer_byte(&g_sensorhub_bus, value);
    sensorhub_end_transaction(sensor->port, sensor->pin);
}

static void sensorhub_prime_link(void)
{
    uint8_t discard = 0U;

    /*
     * Proteus can corrupt the very first SensorHub frame right after both MCUs
     * leave reset. Prime the link once and throw the result away.
     */
    (void)sensorhub_read_reg_u8(&g_sensor_imu, IMU_WHO_AM_I_REG, &discard);
    HAL_Delay(1);
}

static uint8_t sensorhub_selftest_and_configure(void)
{
    uint8_t ok = 1U;
    uint8_t who = 0U;

    uart_puts("[SELFTEST] SensorHub link...\r\n");

    if (!sensorhub_read_reg_u8_retry(&g_sensor_imu, IMU_WHO_AM_I_REG, &who, 3U) || who != IMU_WHO_AM_I_VAL) {
        uart_printf("    IMU WHO=0x%02X EXPECTED=0x%02X FAIL\r\n", who, IMU_WHO_AM_I_VAL);
        ok = 0U;
    } else {
        uart_printf("    IMU WHO=0x%02X OK\r\n", who);
        sensorhub_write_reg(&g_sensor_imu, IMU_CTRL1_XL_REG, 0x94);
        sensorhub_write_reg(&g_sensor_imu, IMU_CTRL2_G_REG, 0x9D);
    }

    if (!sensorhub_read_reg_u8_retry(&g_sensor_highg_l, HIGHG_WHO_AM_I_REG, &who, 3U) || who != HIGHG_WHO_AM_I_VAL) {
        uart_printf("    HIGHG_L WHO=0x%02X EXPECTED=0x%02X FAIL\r\n", who, HIGHG_WHO_AM_I_VAL);
        ok = 0U;
    } else {
        uart_printf("    HIGHG_L WHO=0x%02X OK\r\n", who);
        sensorhub_write_reg(&g_sensor_highg_l, HIGHG_CTRL1_REG, 0x27);
    }

    if (!sensorhub_read_reg_u8_retry(&g_sensor_highg_r, HIGHG_WHO_AM_I_REG, &who, 3U) || who != HIGHG_WHO_AM_I_VAL) {
        uart_printf("    HIGHG_R WHO=0x%02X EXPECTED=0x%02X FAIL\r\n", who, HIGHG_WHO_AM_I_VAL);
        ok = 0U;
    } else {
        uart_printf("    HIGHG_R WHO=0x%02X OK\r\n", who);
        sensorhub_write_reg(&g_sensor_highg_r, HIGHG_CTRL1_REG, 0x27);
    }

    if (!sensorhub_read_reg_u8_retry(&g_sensor_kp200_l, KP200_WHO_AM_I_REG, &who, 3U) || who != KP200_L_WHO_AM_I_VAL) {
        uart_printf("    KP200_L WHO=0x%02X EXPECTED=0x%02X FAIL\r\n", who, KP200_L_WHO_AM_I_VAL);
        ok = 0U;
    } else {
        uart_printf("    KP200_L WHO=0x%02X OK\r\n", who);
        sensorhub_write_reg(&g_sensor_kp200_l, KP200_CTRL_REG, 0x01);
    }

    if (!sensorhub_read_reg_u8_retry(&g_sensor_kp200_r, KP200_WHO_AM_I_REG, &who, 3U) || who != KP200_R_WHO_AM_I_VAL) {
        uart_printf("    KP200_R WHO=0x%02X EXPECTED=0x%02X FAIL\r\n", who, KP200_R_WHO_AM_I_VAL);
        ok = 0U;
    } else {
        uart_printf("    KP200_R WHO=0x%02X OK\r\n", who);
        sensorhub_write_reg(&g_sensor_kp200_r, KP200_CTRL_REG, 0x01);
    }

    sensorhub_release_all_cs();
    return ok;
}

static uint8_t imu_read(imu_data_t *data)
{
    uint8_t status = 0U;
    uint8_t raw[12];
    int16_t raw_gx;
    int16_t raw_gy;
    int16_t raw_gz;
    int16_t raw_ax;
    int16_t raw_ay;
    int16_t raw_az;

    if (!sensorhub_read_reg_u8(&g_sensor_imu, IMU_STATUS_REG, &status)) {
        data->valid = 0U;
        return 0U;
    }

    if ((status & EMU_STATUS_DRDY) == 0U) {
        data->valid = 0U;
        return 1U;
    }

    (void)sensorhub_read_regs(&g_sensor_imu, IMU_OUTX_L_G_REG, raw, 12U);

    raw_gx = le16_to_s16(&raw[0]);
    raw_gy = le16_to_s16(&raw[2]);
    raw_gz = le16_to_s16(&raw[4]);
    raw_ax = le16_to_s16(&raw[6]);
    raw_ay = le16_to_s16(&raw[8]);
    raw_az = le16_to_s16(&raw[10]);

    data->gx = (float)raw_gx * IMU_GYRO_DPS_PER_LSB;
    data->gy = (float)raw_gy * IMU_GYRO_DPS_PER_LSB;
    data->gz = (float)raw_gz * IMU_GYRO_DPS_PER_LSB;
    data->ax = (float)raw_ax * IMU_ACCEL_G_PER_LSB * G_TO_MS2;
    data->ay = (float)raw_ay * IMU_ACCEL_G_PER_LSB * G_TO_MS2;
    data->az = (float)raw_az * IMU_ACCEL_G_PER_LSB * G_TO_MS2;
    data->valid = 1U;

    return 1U;
}

static uint8_t highg_read(const struct sensor_desc *sensor, highg_data_t *data)
{
    uint8_t status = 0U;
    uint8_t raw[6];
    int16_t raw_x;
    int16_t raw_y;
    int16_t raw_z;

    if (!sensorhub_read_reg_u8(sensor, HIGHG_STATUS_REG, &status)) {
        data->valid = 0U;
        return 0U;
    }

    if ((status & EMU_STATUS_DRDY) == 0U) {
        data->valid = 0U;
        return 1U;
    }

    (void)sensorhub_read_regs(sensor, HIGHG_OUT_X_L_REG, raw, 6U);

    raw_x = le16_to_s16(&raw[0]);
    raw_y = le16_to_s16(&raw[2]);
    raw_z = le16_to_s16(&raw[4]);

    data->ax = (float)raw_x * HIGHG_G_PER_LSB * G_TO_MS2;
    data->ay = (float)raw_y * HIGHG_G_PER_LSB * G_TO_MS2;
    data->az = (float)raw_z * HIGHG_G_PER_LSB * G_TO_MS2;
    data->valid = 1U;

    return 1U;
}

static uint8_t kp200_read(const struct sensor_desc *sensor, kp200_data_t *data)
{
    uint8_t status = 0U;
    uint8_t pressure_raw[2];

    if (!sensorhub_read_reg_u8(sensor, KP200_STATUS_REG, &status)) {
        data->valid = 0U;
        data->fault = 1U;
        return 0U;
    }

    data->fault = (status & EMU_STATUS_FAULT) ? 1U : 0U;
    if ((status & EMU_STATUS_DRDY) == 0U) {
        data->valid = 0U;
        return 1U;
    }

    (void)sensorhub_read_regs(sensor, KP200_PRESSURE_H_REG, pressure_raw, 2U);
    data->dp_kpa = (float)be16_to_s16(pressure_raw) / 1000.0f;
    data->valid = data->fault ? 0U : 1U;

    return 1U;
}

static uint8_t sample_all_sensors(sensor_snapshot_t *snapshot)
{
    memset(snapshot, 0, sizeof(*snapshot));

    if (!imu_read(&snapshot->imu)) {
        return 0U;
    }
    if (!highg_read(&g_sensor_highg_l, &snapshot->highg_l)) {
        return 0U;
    }
    if (!highg_read(&g_sensor_highg_r, &snapshot->highg_r)) {
        return 0U;
    }
    if (!kp200_read(&g_sensor_kp200_l, &snapshot->kp200_l)) {
        return 0U;
    }
    if (!kp200_read(&g_sensor_kp200_r, &snapshot->kp200_r)) {
        return 0U;
    }

    if (snapshot->imu.valid) snapshot->flags |= SENSOR_FLAG_IMU;
    if (snapshot->highg_l.valid) snapshot->flags |= SENSOR_FLAG_HIGHG_L;
    if (snapshot->highg_r.valid) snapshot->flags |= SENSOR_FLAG_HIGHG_R;
    if (snapshot->kp200_l.valid) snapshot->flags |= SENSOR_FLAG_KP200_L;
    if (snapshot->kp200_r.valid) snapshot->flags |= SENSOR_FLAG_KP200_R;

    return 1U;
}

static void actuator_edr_gpio_bus_init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    GPIO_InitStruct.Pin = GPIO_PIN_13 | GPIO_PIN_15;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_14;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = EDR_CS_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(EDR_CS_GPIO_Port, &GPIO_InitStruct);

    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_13 | GPIO_PIN_15, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(EDR_CS_GPIO_Port, EDR_CS_Pin, GPIO_PIN_SET);
}

static void actuator_edr_release_all_cs(void)
{
    HAL_GPIO_WritePin(CS_SQUIB_GPIO_Port, CS_SQUIB_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(EDR_CS_GPIO_Port, EDR_CS_Pin, GPIO_PIN_SET);
}

static void actuator_edr_begin_squib(void)
{
    actuator_edr_release_all_cs();
    soft_spi_select_delay();
    HAL_GPIO_WritePin(CS_SQUIB_GPIO_Port, CS_SQUIB_Pin, GPIO_PIN_RESET);
    soft_spi_select_delay();
}

static void actuator_edr_begin_edr(void)
{
    actuator_edr_release_all_cs();
    soft_spi_select_delay();
    HAL_GPIO_WritePin(EDR_CS_GPIO_Port, EDR_CS_Pin, GPIO_PIN_RESET);
    soft_spi_select_delay();
}

static void actuator_edr_end_transaction(GPIO_TypeDef *cs_port, uint16_t cs_pin)
{
    soft_spi_select_delay();
    HAL_GPIO_WritePin(cs_port, cs_pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(g_actuator_edr_bus.sck_port, g_actuator_edr_bus.sck_pin, GPIO_PIN_RESET);
    soft_spi_select_delay();
}

static void squib_send_command(uint8_t cmd)
{
    actuator_edr_begin_squib();
    (void)soft_spi_transfer_byte(&g_actuator_edr_bus, cmd);
    actuator_edr_end_transaction(CS_SQUIB_GPIO_Port, CS_SQUIB_Pin);
}

static void test_squib_visual(void)
{
    squib_send_command(SQUIB_CMD_ALL_OFF);
    uart_puts("    VISUAL CMD ALL_OFF\r\n");
    HAL_Delay(200);

    squib_send_command(SQUIB_MASK_FRONT);
    uart_puts("    VISUAL CMD FRONT\r\n");
    HAL_Delay(250);

    squib_send_command(SQUIB_MASK_BELT);
    uart_puts("    VISUAL CMD BELT\r\n");
    HAL_Delay(250);

    squib_send_command(SQUIB_MASK_SIDE_L);
    uart_puts("    VISUAL CMD SIDE_L\r\n");
    HAL_Delay(250);

    squib_send_command(SQUIB_MASK_SIDE_R);
    uart_puts("    VISUAL CMD SIDE_R\r\n");
    HAL_Delay(250);

    squib_send_command(SQUIB_MASK_ROLLOVER);
    uart_puts("    VISUAL CMD ROLLOVER\r\n");
    HAL_Delay(250);

    squib_send_command(SQUIB_CMD_ALL_ON);
    uart_puts("    VISUAL CMD ALL_ON\r\n");
    HAL_Delay(600);

    squib_send_command(SQUIB_CMD_ALL_OFF);
    uart_puts("    VISUAL CMD ALL_OFF\r\n");
}

static void edr_write_reg(uint8_t addr, uint8_t value)
{
    actuator_edr_begin_edr();
    (void)soft_spi_transfer_byte(&g_actuator_edr_bus, (uint8_t)(addr & 0x7FU));
    soft_spi_interbyte_delay();
    (void)soft_spi_transfer_byte(&g_actuator_edr_bus, value);
    actuator_edr_end_transaction(EDR_CS_GPIO_Port, EDR_CS_Pin);
}

static uint8_t edr_read_reg(uint8_t addr)
{
    uint8_t value;

    actuator_edr_begin_edr();
    (void)soft_spi_transfer_byte(&g_actuator_edr_bus, (uint8_t)(SENSOR_PROTO_READ_BIT | (addr & 0x7FU)));
    soft_spi_interbyte_delay();
    value = soft_spi_transfer_byte(&g_actuator_edr_bus, 0x00);
    actuator_edr_end_transaction(EDR_CS_GPIO_Port, EDR_CS_Pin);

    return value;
}

static uint8_t edr_test_link(void)
{
    uint8_t who = edr_read_reg(EDR_REG_WHO_AM_I);
    uint8_t fault = edr_read_reg(EDR_REG_FAULT);

    uart_puts("[SELFTEST] EDR link...\r\n");
    if (who != EDR_WHO_AM_I) {
        uart_printf("    EDR WHO=0x%02X EXPECTED=0x%02X FAIL\r\n", who, EDR_WHO_AM_I);
        return 0U;
    }

    if (fault != 0x00U) {
        uart_printf("    EDR FAULT=0x%02X FAIL\r\n", fault);
        return 0U;
    }

    uart_printf("    EDR WHO=0x%02X OK\r\n", who);
    return 1U;
}

static void edr_clear_log(void)
{
    edr_write_reg(EDR_REG_CTRL, EDR_CTRL_CLEAR_STATUS | EDR_CTRL_CLEAR_LOG);
}

static void edr_log_boot(uint8_t scenario_inputs)
{
    edr_write_reg(EDR_REG_STAGE, EDR_STAGE_BOOT);
    edr_write_reg(EDR_REG_SCENARIO_INPUTS, scenario_inputs);
    edr_write_reg(EDR_REG_SENSOR_FLAGS, 0x00);
    edr_write_reg(EDR_REG_HOST_EVENT_ID, EDR_HOST_EVENT_BOOT);
    edr_write_reg(EDR_REG_HOST_FLAGS, 0x00);
    edr_write_reg(EDR_REG_HOST_DATA0, 0x01);
    edr_write_reg(EDR_REG_HOST_DATA1, scenario_inputs & INPUT_SCENARIO_MASK);
}

static void edr_log_selftest_ok(void)
{
    edr_write_reg(EDR_REG_STAGE, EDR_STAGE_SELFTEST);
    edr_write_reg(EDR_REG_SENSOR_FLAGS, SENSOR_FLAG_ALL);
    edr_write_reg(EDR_REG_HOST_EVENT_ID, EDR_HOST_EVENT_SELFTEST_OK);
    edr_write_reg(EDR_REG_HOST_FLAGS, EDR_HOST_FLAG_SENSOR_OK);
    edr_write_reg(EDR_REG_HOST_DATA0, SENSOR_FLAG_ALL);
    edr_write_reg(EDR_REG_HOST_DATA1, 0x00);
}

static void edr_log_ready(void)
{
    edr_write_reg(EDR_REG_STAGE, EDR_STAGE_READY);
}

static void edr_log_monitor(uint8_t scenario_inputs, uint8_t sensor_flags)
{
    edr_write_reg(EDR_REG_STAGE, EDR_STAGE_MONITOR);
    edr_write_reg(EDR_REG_SCENARIO_INPUTS, scenario_inputs);
    edr_write_reg(EDR_REG_SENSOR_FLAGS, sensor_flags);
}

static void edr_log_deploy(crash_event_t event, uint8_t squib_mask, uint8_t scenario_inputs, uint8_t sensor_flags)
{
    edr_write_reg(EDR_REG_STAGE, EDR_STAGE_DEPLOYED);
    edr_write_reg(EDR_REG_SCENARIO_INPUTS, scenario_inputs);
    edr_write_reg(EDR_REG_SENSOR_FLAGS, sensor_flags);
    edr_write_reg(EDR_REG_HOST_EVENT_ID, event_to_edr_host_id(event));
    edr_write_reg(EDR_REG_HOST_FLAGS, EDR_HOST_FLAG_SENSOR_OK | EDR_HOST_FLAG_DEPLOYED);
    edr_write_reg(EDR_REG_HOST_DATA0, squib_mask);
    edr_write_reg(EDR_REG_HOST_DATA1, (uint8_t)(scenario_inputs & INPUT_SCENARIO_MASK));
}

static void edr_log_visual_complete(void)
{
    edr_write_reg(EDR_REG_STAGE, EDR_STAGE_VISUAL);
    edr_write_reg(EDR_REG_HOST_EVENT_ID, EDR_HOST_EVENT_VISUAL);
    edr_write_reg(EDR_REG_HOST_FLAGS, EDR_HOST_FLAG_VISUAL_DONE);
    edr_write_reg(EDR_REG_HOST_DATA0, SQUIB_CMD_ALL_ON);
    edr_write_reg(EDR_REG_HOST_DATA1, SQUIB_CMD_ALL_OFF);
}

static void edr_log_fault(uint8_t scenario_inputs, uint8_t sensor_flags)
{
    edr_write_reg(EDR_REG_STAGE, EDR_STAGE_FAULT);
    edr_write_reg(EDR_REG_SCENARIO_INPUTS, scenario_inputs);
    edr_write_reg(EDR_REG_SENSOR_FLAGS, sensor_flags);
    edr_write_reg(EDR_REG_HOST_EVENT_ID, EDR_HOST_EVENT_FAULT);
    edr_write_reg(EDR_REG_HOST_FLAGS, EDR_HOST_FLAG_FAULT);
    edr_write_reg(EDR_REG_HOST_DATA0, sensor_flags);
    edr_write_reg(EDR_REG_HOST_DATA1, (uint8_t)(scenario_inputs & INPUT_SCENARIO_MASK));
}

static void edr_dump_summary(void)
{
    uint8_t who = edr_read_reg(EDR_REG_WHO_AM_I);
    uint8_t status = edr_read_reg(EDR_REG_STATUS);
    uint8_t stage = edr_read_reg(EDR_REG_STAGE);
    uint8_t scenario = edr_read_reg(EDR_REG_SCENARIO_INPUTS);
    uint8_t sensor_flags = edr_read_reg(EDR_REG_SENSOR_FLAGS);
    uint8_t last_cmd = edr_read_reg(EDR_REG_LAST_SQUIB_CMD);
    uint8_t output_mask = edr_read_reg(EDR_REG_SQUIB_OUTPUT_MASK);
    uint8_t fault = edr_read_reg(EDR_REG_FAULT);
    uint16_t transactions = ((uint16_t)edr_read_reg(EDR_REG_TRANSACTION_H) << 8) |
                            (uint16_t)edr_read_reg(EDR_REG_TRANSACTION_L);

    uart_printf("    EDR WHO=0x%02X STATUS=0x%02X STAGE=0x%02X\r\n", who, status, stage);
    uart_printf("    SCENARIO=0x%02X SENSOR_FLAGS=0x%02X\r\n", scenario, sensor_flags);
    uart_printf("    LAST_SQUIB_CMD=0x%02X OUTPUT_MASK=0x%02X\r\n", last_cmd, output_mask);
    uart_printf("    FAULT=0x%02X TX_COUNT=%u\r\n", fault, transactions);
    uart_printf("    TIM3_MISSED=%lu\r\n", (unsigned long)g_tick_2khz_missed);
}

static void tim3_init_2khz(void)
{
    __HAL_RCC_TIM3_CLK_ENABLE();

    TIM3->CR1 = 0x0000U;
    TIM3->PSC = 15U;
    TIM3->ARR = 499U;
    TIM3->CNT = 0U;
    TIM3->DIER |= TIM_DIER_UIE;
    TIM3->EGR |= TIM_EGR_UG;

    HAL_NVIC_SetPriority(TIM3_IRQn, 2, 0);
    HAL_NVIC_EnableIRQ(TIM3_IRQn);

    TIM3->CR1 |= TIM_CR1_CEN;
}

static uint8_t cross_validate_frontal(const sensor_snapshot_t *snapshot)
{
    uint8_t votes = 0U;

    if (snapshot->imu.ax <= -FRONT_IMU_TH_MS2) {
        votes++;
    }
    if (snapshot->highg_l.ax <= -FRONT_HIGHG_TH_MS2) {
        votes++;
    }
    if (snapshot->highg_r.ax <= -FRONT_HIGHG_TH_MS2) {
        votes++;
    }

    return votes >= 2U;
}

static uint8_t cross_validate_side_left(const sensor_snapshot_t *snapshot)
{
    return (snapshot->imu.ay >= SIDE_IMU_TH_MS2) &&
           (snapshot->highg_l.ay >= SIDE_HIGHG_TH_MS2) &&
           (snapshot->kp200_l.dp_kpa >= SIDE_PPS_TH_KPA);
}

static uint8_t cross_validate_side_right(const sensor_snapshot_t *snapshot)
{
    return (snapshot->imu.ay <= -SIDE_IMU_TH_MS2) &&
           (snapshot->highg_r.ay <= -SIDE_HIGHG_TH_MS2) &&
           (snapshot->kp200_r.dp_kpa >= SIDE_PPS_TH_KPA);
}

static uint8_t cross_validate_rear(const sensor_snapshot_t *snapshot)
{
    uint8_t votes = 0U;

    if (snapshot->imu.ax >= REAR_IMU_TH_MS2) {
        votes++;
    }
    if (snapshot->highg_l.ax >= REAR_HIGHG_TH_MS2) {
        votes++;
    }
    if (snapshot->highg_r.ax >= REAR_HIGHG_TH_MS2) {
        votes++;
    }

    return votes >= 2U;
}

static uint8_t cross_validate_rollover(const sensor_snapshot_t *snapshot)
{
    return (f_abs(snapshot->imu.gx) >= ROLLOVER_GX_TH_DPS) &&
           (f_abs(snapshot->imu.ay) >= ROLLOVER_AY_TH_MS2);
}

static void update_safing_gate(safing_gate_t *gate, float a_independent, float threshold_ms, float dt_s, float idle_threshold_ms2)
{
    if (f_abs(a_independent) >= idle_threshold_ms2) {
        gate->dv_ms += f_abs(a_independent) * dt_s;
        gate->window_ticks++;
        gate->idle_ticks = 0U;

        if (gate->window_ticks > SAFING_WINDOW_TICKS) {
            gate->dv_ms = 0.0f;
            gate->window_ticks = 1U;
        }

        if (gate->dv_ms >= threshold_ms) {
            gate->armed = 1U;
        }
    } else {
        gate->window_ticks = 0U;
        gate->dv_ms = 0.0f;

        if (gate->armed) {
            if (gate->idle_ticks < 0xFFFFU) {
                gate->idle_ticks++;
            }

            if (gate->idle_ticks >= SAFING_REARM_TICKS) {
                gate->armed = 0U;
                gate->idle_ticks = 0U;
            }
        }
    }
}

static void update_jerk_gate(jerk_gate_t *gate, float a_current, float dt_s, float energy_min, float energy_max, uint8_t active)
{
    float jerk;

    if (!active) {
        gate->energy = 0.0f;
        gate->samples = 0U;
        gate->initialized = 0U;
        gate->is_crash = 0U;
        gate->last_a = 0.0f;
        return;
    }

    if (!gate->initialized) {
        gate->last_a = a_current;
        gate->initialized = 1U;
        return;
    }

    jerk = (a_current - gate->last_a) / dt_s;
    gate->energy += jerk * jerk * dt_s;
    gate->last_a = a_current;
    gate->samples++;

    if (gate->samples >= JERK_WINDOW_TICKS) {
        if ((gate->energy >= energy_min) && (gate->energy <= energy_max)) {
            gate->is_crash = 1U;
        }
        gate->samples = 0U;
        gate->energy = 0.0f;
    }
}

static void update_oscillation_gate(osc_gate_t *gate, int8_t sign, uint8_t active)
{
    if (!active) {
        gate->last_sign = 0;
        gate->sign_changes = 0U;
        gate->samples = 0U;
        gate->is_oscillation = 0U;
        return;
    }

    if ((sign != 0) && (gate->last_sign != 0) && (sign != gate->last_sign)) {
        gate->sign_changes++;
    }

    if (sign != 0) {
        gate->last_sign = sign;
    }

    gate->samples++;
    if (gate->samples >= OSC_WINDOW_TICKS) {
        if (gate->sign_changes > OSC_SIGN_CHANGE_LIMIT) {
            gate->is_oscillation = 1U;
        }
        gate->samples = 0U;
        gate->sign_changes = 0U;
        gate->last_sign = sign;
    }
}

static void decision_reset(decision_state_t *state)
{
    memset(state, 0, sizeof(*state));
}

static crash_event_t evaluate_event(const sensor_snapshot_t *snapshot, decision_state_t *state, float dt_s)
{
    float decel_x = (snapshot->imu.ax < 0.0f) ? -snapshot->imu.ax : 0.0f;
    float accel_rear_x = (snapshot->imu.ax > 0.0f) ? snapshot->imu.ax : 0.0f;
    float accel_side_left_y = (snapshot->imu.ay > 0.0f) ? snapshot->imu.ay : 0.0f;
    float accel_side_right_y = (snapshot->imu.ay < 0.0f) ? -snapshot->imu.ay : 0.0f;
    float a_total_yz;
    float phi_acc_deg;
    float alpha_eff;
    float dphi_deg;
    float front_ds;
    float front_e_threshold;
    int8_t ax_sign = sign_with_deadband(snapshot->imu.ax, FRONT_ONSET_TH_MS2);
    int8_t ay_sign = sign_with_deadband(snapshot->imu.ay, SIDE_ONSET_TH_MS2);
    int8_t gx_sign = sign_with_deadband(snapshot->imu.gx, ROLLOVER_ONSET_DPS);
    uint8_t front_active = (snapshot->imu.ax <= -FRONT_ONSET_TH_MS2);
    uint8_t side_left_active = (snapshot->imu.ay >= SIDE_ONSET_TH_MS2) || (snapshot->kp200_l.dp_kpa > 0.5f);
    uint8_t side_right_active = (snapshot->imu.ay <= -SIDE_ONSET_TH_MS2) || (snapshot->kp200_r.dp_kpa > 0.5f);
    uint8_t rear_active = (snapshot->imu.ax >= REAR_ONSET_TH_MS2);
    uint8_t rollover_active = (f_abs(snapshot->imu.gx) >= ROLLOVER_ONSET_DPS);

    if (front_active) {
        state->front_duration_ticks++;
        update_safing_gate(&state->safing_front,
                           ((snapshot->highg_l.ax + snapshot->highg_r.ax) * -0.5f),
                           FRONT_DV_THRESHOLD_MS,
                           dt_s,
                           SAFING_IDLE_AX_MS2);
        update_jerk_gate(&state->jerk_front,
                         snapshot->imu.ax,
                         dt_s,
                         JERK_FRONT_MIN,
                         JERK_FRONT_MAX,
                         front_active);
        update_oscillation_gate(&state->osc_front, ax_sign, front_active);

        if (!state->front_red.started && (decel_x >= FRONT_RED_B_MS2)) {
            state->front_red.started = 1U;
            state->front_red.last_a_ms2 = decel_x;
        }

        if (state->front_red.started) {
            state->front_red.v_ms += 0.5f * (state->front_red.last_a_ms2 + decel_x) * dt_s;
            front_ds = state->front_red.v_ms * dt_s;
            state->front_red.s_m += front_ds;
            if (decel_x > FRONT_RED_B_MS2) {
                state->front_red.e_res += (decel_x - FRONT_RED_B_MS2) * front_ds;
            }
            state->front_red.last_a_ms2 = decel_x;

            if (state->front_red.s_m >= FRONT_RED_S0_M) {
                front_e_threshold = FRONT_RED_E0 + (FRONT_RED_SLOPE_M * (FRONT_RED_S0_M - state->front_red.s_m));
                if (state->front_red.e_res >= front_e_threshold) {
                    state->front_red.should_deploy = 1U;
                }
            }
        }

        if (cross_validate_frontal(snapshot)) {
            if (state->front_count < 0xFFU) {
                state->front_count++;
            }
        } else {
            state->front_count = 0U;
        }
    } else {
        state->front_duration_ticks = 0U;
        state->front_count = 0U;
        memset(&state->front_red, 0, sizeof(state->front_red));
        update_safing_gate(&state->safing_front, 0.0f, FRONT_DV_THRESHOLD_MS, dt_s, SAFING_IDLE_AX_MS2);
        update_jerk_gate(&state->jerk_front, 0.0f, dt_s, JERK_FRONT_MIN, JERK_FRONT_MAX, 0U);
        update_oscillation_gate(&state->osc_front, 0, 0U);
    }

    if (side_left_active) {
        state->side_left_duration_ticks++;
        state->side_left_red.dv_ms += accel_side_left_y * dt_s;
        state->side_left_red.energy += accel_side_left_y * accel_side_left_y * dt_s;
        update_safing_gate(&state->safing_side_left,
                           snapshot->highg_l.ay,
                           SIDE_DV_THRESHOLD_MS,
                           dt_s,
                           SAFING_IDLE_AY_MS2);
        update_jerk_gate(&state->jerk_side_left,
                         snapshot->imu.ay,
                         dt_s,
                         JERK_SIDE_MIN,
                         JERK_SIDE_MAX,
                         side_left_active);
        update_oscillation_gate(&state->osc_side_left, ay_sign, side_left_active);

        if ((state->side_left_red.dv_ms >= SIDE_DV_THRESHOLD_MS) &&
            (state->side_left_red.energy >= SIDE_RED_ENERGY_THRESHOLD)) {
            state->side_left_red.should_deploy = 1U;
        }

        if (cross_validate_side_left(snapshot)) {
            if (state->side_left_count < 0xFFU) {
                state->side_left_count++;
            }
        } else {
            state->side_left_count = 0U;
        }
    } else {
        state->side_left_duration_ticks = 0U;
        state->side_left_count = 0U;
        memset(&state->side_left_red, 0, sizeof(state->side_left_red));
        update_safing_gate(&state->safing_side_left, 0.0f, SIDE_DV_THRESHOLD_MS, dt_s, SAFING_IDLE_AY_MS2);
        update_jerk_gate(&state->jerk_side_left, 0.0f, dt_s, JERK_SIDE_MIN, JERK_SIDE_MAX, 0U);
        update_oscillation_gate(&state->osc_side_left, 0, 0U);
    }

    if (side_right_active) {
        state->side_right_duration_ticks++;
        state->side_right_red.dv_ms += accel_side_right_y * dt_s;
        state->side_right_red.energy += accel_side_right_y * accel_side_right_y * dt_s;
        update_safing_gate(&state->safing_side_right,
                           -snapshot->highg_r.ay,
                           SIDE_DV_THRESHOLD_MS,
                           dt_s,
                           SAFING_IDLE_AY_MS2);
        update_jerk_gate(&state->jerk_side_right,
                         -snapshot->imu.ay,
                         dt_s,
                         JERK_SIDE_MIN,
                         JERK_SIDE_MAX,
                         side_right_active);
        update_oscillation_gate(&state->osc_side_right, (int8_t)-ay_sign, side_right_active);

        if ((state->side_right_red.dv_ms >= SIDE_DV_THRESHOLD_MS) &&
            (state->side_right_red.energy >= SIDE_RED_ENERGY_THRESHOLD)) {
            state->side_right_red.should_deploy = 1U;
        }

        if (cross_validate_side_right(snapshot)) {
            if (state->side_right_count < 0xFFU) {
                state->side_right_count++;
            }
        } else {
            state->side_right_count = 0U;
        }
    } else {
        state->side_right_duration_ticks = 0U;
        state->side_right_count = 0U;
        memset(&state->side_right_red, 0, sizeof(state->side_right_red));
        update_safing_gate(&state->safing_side_right, 0.0f, SIDE_DV_THRESHOLD_MS, dt_s, SAFING_IDLE_AY_MS2);
        update_jerk_gate(&state->jerk_side_right, 0.0f, dt_s, JERK_SIDE_MIN, JERK_SIDE_MAX, 0U);
        update_oscillation_gate(&state->osc_side_right, 0, 0U);
    }

    if (rear_active) {
        state->rear_duration_ticks++;
        state->rear_logic.dv_ms += accel_rear_x * dt_s;
        update_safing_gate(&state->safing_rear,
                           ((snapshot->highg_l.ax + snapshot->highg_r.ax) * 0.5f),
                           REAR_DV_THRESHOLD_MS,
                           dt_s,
                           SAFING_IDLE_AX_MS2);
        update_oscillation_gate(&state->osc_rear, ax_sign, rear_active);

        if (state->rear_logic.dv_ms >= REAR_DV_THRESHOLD_MS) {
            state->rear_logic.detected = 1U;
        }

        if (cross_validate_rear(snapshot)) {
            if (state->rear_count < 0xFFU) {
                state->rear_count++;
            }
        } else {
            state->rear_count = 0U;
        }
    } else {
        state->rear_duration_ticks = 0U;
        state->rear_count = 0U;
        memset(&state->rear_logic, 0, sizeof(state->rear_logic));
        update_safing_gate(&state->safing_rear, 0.0f, REAR_DV_THRESHOLD_MS, dt_s, SAFING_IDLE_AX_MS2);
        update_oscillation_gate(&state->osc_rear, 0, 0U);
    }

    a_total_yz = sqrtf((snapshot->imu.ay * snapshot->imu.ay) + (snapshot->imu.az * snapshot->imu.az));
    alpha_eff = (f_abs(a_total_yz - G_TO_MS2) < ROLLOVER_HIGHG_FREEZE_BAND) ? ROLLOVER_FILTER_ALPHA : 1.0f;
    phi_acc_deg = atan2f(snapshot->imu.ay, snapshot->imu.az) * RAD_TO_DEG;
    state->prev_roll_angle_deg = state->roll_angle_deg;
    state->roll_angle_deg = alpha_eff * (state->roll_angle_deg + (snapshot->imu.gx * dt_s)) +
                            ((1.0f - alpha_eff) * phi_acc_deg);
    dphi_deg = state->roll_angle_deg - state->prev_roll_angle_deg;

    if (rollover_active) {
        state->rollover_duration_ticks++;
        state->rollover_phase_metric =
            ((snapshot->imu.gx * snapshot->imu.gx) / (ROLLOVER_GX_TH_DPS * ROLLOVER_GX_TH_DPS)) +
            ((state->roll_angle_deg * state->roll_angle_deg) / (ROLLOVER_PHI_CRITICAL_DEG * ROLLOVER_PHI_CRITICAL_DEG));
        update_safing_gate(&state->safing_rollover,
                           f_abs(snapshot->highg_l.ay),
                           ROLLOVER_SAFING_DV_MS,
                           dt_s,
                           SAFING_IDLE_AY_MS2);
        update_oscillation_gate(&state->osc_gyro, gx_sign, rollover_active);

        if ((dphi_deg * snapshot->imu.gx) > 0.0f && (f_abs(snapshot->imu.gx) >= ROLLOVER_ARMING_DPS)) {
            if (state->rollover_monotonic_ticks < 0xFFFFU) {
                state->rollover_monotonic_ticks++;
            }
        } else {
            state->rollover_monotonic_ticks = 0U;
        }

        if ((state->rollover_phase_metric >= 1.0f) &&
            (f_abs(snapshot->imu.ay) >= ROLLOVER_AY_TH_MS2) &&
            (f_abs(state->roll_angle_deg) >= ROLLOVER_PHI_TH_DEG)) {
            if (state->rollover_count < 0xFFU) {
                state->rollover_count++;
            }
        } else {
            state->rollover_count = 0U;
        }
    } else {
        state->rollover_duration_ticks = 0U;
        state->rollover_count = 0U;
        state->rollover_phase_metric = 0.0f;
        state->rollover_monotonic_ticks = 0U;
        update_safing_gate(&state->safing_rollover, 0.0f, ROLLOVER_SAFING_DV_MS, dt_s, SAFING_IDLE_AY_MS2);
        update_oscillation_gate(&state->osc_gyro, 0, 0U);
        if (f_abs(state->roll_angle_deg) < 1.0f) {
            state->roll_angle_deg = 0.0f;
        }
    }

    if (state->front_red.should_deploy &&
        (state->front_count >= FRONT_CONFIRM_TICKS) &&
        (state->front_duration_ticks >= PLAUSIBILITY_FRONT_MIN_TICKS) &&
        (state->front_duration_ticks <= PLAUSIBILITY_FRONT_MAX_TICKS) &&
        state->safing_front.armed &&
        state->jerk_front.is_crash &&
        !state->osc_front.is_oscillation) {
        return CRASH_EVENT_FRONT;
    }

    if (state->side_left_red.should_deploy &&
        (state->side_left_count >= SIDE_CONFIRM_TICKS) &&
        (state->side_left_duration_ticks >= PLAUSIBILITY_SIDE_MIN_TICKS) &&
        (state->side_left_duration_ticks <= PLAUSIBILITY_SIDE_MAX_TICKS) &&
        state->safing_side_left.armed &&
        state->jerk_side_left.is_crash &&
        !state->osc_side_left.is_oscillation) {
        return CRASH_EVENT_SIDE_LEFT;
    }

    if (state->side_right_red.should_deploy &&
        (state->side_right_count >= SIDE_CONFIRM_TICKS) &&
        (state->side_right_duration_ticks >= PLAUSIBILITY_SIDE_MIN_TICKS) &&
        (state->side_right_duration_ticks <= PLAUSIBILITY_SIDE_MAX_TICKS) &&
        state->safing_side_right.armed &&
        state->jerk_side_right.is_crash &&
        !state->osc_side_right.is_oscillation) {
        return CRASH_EVENT_SIDE_RIGHT;
    }

    if (state->rear_logic.detected &&
        (state->rear_count >= REAR_CONFIRM_TICKS) &&
        (state->rear_duration_ticks >= PLAUSIBILITY_REAR_MIN_TICKS) &&
        (state->rear_duration_ticks <= PLAUSIBILITY_REAR_MAX_TICKS) &&
        state->safing_rear.armed &&
        !state->osc_rear.is_oscillation) {
        return CRASH_EVENT_REAR;
    }

    if ((state->rollover_count >= ROLLOVER_CONFIRM_TICKS) &&
        (state->rollover_duration_ticks >= PLAUSIBILITY_ROLLOVER_MIN_TICKS) &&
        (state->rollover_duration_ticks <= PLAUSIBILITY_ROLLOVER_MAX_TICKS) &&
        state->safing_rollover.armed &&
        !state->osc_gyro.is_oscillation &&
        (state->rollover_monotonic_ticks >= ROLLOVER_MONOTONIC_TICKS) &&
        cross_validate_rollover(snapshot)) {
        return CRASH_EVENT_ROLLOVER;
    }

    return CRASH_EVENT_NONE;
}

static void print_decision_metrics(crash_event_t event, const decision_state_t *state)
{
    long a;
    long b;
    long c;

    switch (event) {
    case CRASH_EVENT_FRONT:
        a = (long)(state->front_red.s_m * 10000.0f);
        b = (long)(state->front_red.e_res * 1000.0f);
        c = (long)(state->safing_front.dv_ms * 100.0f);
        uart_printf("    FRONT_RED s_x1e4=%ld e_x1e3=%ld saf_x100=%ld jerk=%u osc=%u\r\n",
                    a, b, c, state->jerk_front.is_crash, state->osc_front.is_oscillation);
        break;
    case CRASH_EVENT_SIDE_LEFT:
        a = (long)(state->side_left_red.dv_ms * 100.0f);
        b = (long)(state->side_left_red.energy * 100.0f);
        c = (long)(state->safing_side_left.dv_ms * 100.0f);
        uart_printf("    SIDE_L dv_x100=%ld e_x100=%ld saf_x100=%ld jerk=%u osc=%u\r\n",
                    a, b, c, state->jerk_side_left.is_crash, state->osc_side_left.is_oscillation);
        break;
    case CRASH_EVENT_SIDE_RIGHT:
        a = (long)(state->side_right_red.dv_ms * 100.0f);
        b = (long)(state->side_right_red.energy * 100.0f);
        c = (long)(state->safing_side_right.dv_ms * 100.0f);
        uart_printf("    SIDE_R dv_x100=%ld e_x100=%ld saf_x100=%ld jerk=%u osc=%u\r\n",
                    a, b, c, state->jerk_side_right.is_crash, state->osc_side_right.is_oscillation);
        break;
    case CRASH_EVENT_REAR:
        a = (long)(state->rear_logic.dv_ms * 100.0f);
        b = (long)(state->safing_rear.dv_ms * 100.0f);
        uart_printf("    REAR dv_x100=%ld saf_x100=%ld osc=%u\r\n",
                    a, b, state->osc_rear.is_oscillation);
        break;
    case CRASH_EVENT_ROLLOVER:
        a = (long)(state->roll_angle_deg * 10.0f);
        b = (long)(state->rollover_phase_metric * 100.0f);
        c = (long)(state->safing_rollover.dv_ms * 100.0f);
        uart_printf("    ROLLOVER phi_x10=%ld F_x100=%ld monotonic=%u saf_x100=%ld\r\n",
                    a, b, state->rollover_monotonic_ticks, c);
        break;
    case CRASH_EVENT_NONE:
    case CRASH_EVENT_VISUAL:
    default:
        break;
    }
}

static uint8_t event_to_squib_mask(crash_event_t event)
{
    switch (event) {
    case CRASH_EVENT_FRONT:
        return SQUIB_CMD_FRONT_RESTRAINTS;
    case CRASH_EVENT_SIDE_LEFT:
        return SQUIB_CMD_SIDE_LEFT;
    case CRASH_EVENT_SIDE_RIGHT:
        return SQUIB_CMD_SIDE_RIGHT;
    case CRASH_EVENT_REAR:
        return SQUIB_CMD_REAR_ONLY;
    case CRASH_EVENT_ROLLOVER:
        return SQUIB_CMD_ROLLOVER_ONLY;
    case CRASH_EVENT_VISUAL:
    case CRASH_EVENT_NONE:
    default:
        return SQUIB_CMD_ALL_OFF;
    }
}

static uint8_t event_to_edr_host_id(crash_event_t event)
{
    switch (event) {
    case CRASH_EVENT_FRONT: return EDR_HOST_EVENT_FRONT;
    case CRASH_EVENT_SIDE_LEFT: return EDR_HOST_EVENT_SIDE_LEFT;
    case CRASH_EVENT_SIDE_RIGHT: return EDR_HOST_EVENT_SIDE_RIGHT;
    case CRASH_EVENT_REAR: return EDR_HOST_EVENT_REAR;
    case CRASH_EVENT_ROLLOVER: return EDR_HOST_EVENT_ROLLOVER;
    case CRASH_EVENT_VISUAL: return EDR_HOST_EVENT_VISUAL;
    case CRASH_EVENT_NONE:
    default: return 0x00;
    }
}

static const char *event_name(crash_event_t event)
{
    switch (event) {
    case CRASH_EVENT_FRONT: return "front";
    case CRASH_EVENT_SIDE_LEFT: return "side_left";
    case CRASH_EVENT_SIDE_RIGHT: return "side_right";
    case CRASH_EVENT_REAR: return "rear";
    case CRASH_EVENT_ROLLOVER: return "rollover";
    case CRASH_EVENT_VISUAL: return "visual";
    case CRASH_EVENT_NONE:
    default: return "none";
    }
}

static uint8_t perform_startup_selftest(uint8_t scenario_inputs)
{
    uint8_t sensors_ok;

    g_state = ACU_STATE_SELFTEST;
    g_last_event = CRASH_EVENT_NONE;
    g_last_squib_cmd = SQUIB_CMD_ALL_OFF;
    g_monitor_scenario = SCENARIO_IDLE;
    g_monitor_start_tick_2khz = 0U;
    g_impact_onset_tick_2khz = 0U;
    g_impact_seen = 0U;
    g_tick_2khz_missed = 0U;
    decision_reset(&g_decision);

    squib_send_command(SQUIB_CMD_ALL_OFF);
    led_all_off();
    sensorhub_release_all_cs();
    actuator_edr_release_all_cs();

    uart_puts("[BOOT] ACU self-test start\r\n");
    uart_printf("[BOOT] Inputs=0x%02X Scenario=%s\r\n", scenario_inputs, scenario_name(scenario_inputs));
    uart_puts("[BOOT] EDR disabled for this bench stage\r\n");
    /*
     * The AVR emulators in Proteus can become observable noticeably later than
     * the STM32 after a common reset. Give the slave side time to leave reset,
     * initialize GPIO/PCINT/timers and start driving its virtual buses before
     * the first self-test transactions.
     */
    HAL_Delay(100);
    sensorhub_release_all_cs();
    HAL_Delay(2);
    sensorhub_prime_link();

    sensors_ok = sensorhub_selftest_and_configure();
    if (!sensors_ok) {
        enter_fault_state(scenario_inputs, 0x00, "SensorHub self-test failed");
        return 0U;
    }

    g_state = ACU_STATE_READY;
    led_set_ready_state();
    uart_puts("[READY] Self-test complete. Press START to monitor.\r\n");
    return 1U;
}

static void enter_fault_state(uint8_t scenario_inputs, uint8_t sensor_flags, const char *reason)
{
    (void)scenario_inputs;
    (void)sensor_flags;
    squib_send_command(SQUIB_CMD_ALL_OFF);
    g_state = ACU_STATE_FAULT;
    led_set_fault_state();
    uart_printf("[FAULT] %s\r\n", reason);
}

void TIM3_IRQHandler(void)
{
    if (TIM3->SR & TIM_SR_UIF) {
        TIM3->SR &= ~TIM_SR_UIF;
        g_tick_2khz_counter++;
    }
}

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);

    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;

    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        Error_Handler();
    }

    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK |
                                  RCC_CLOCKTYPE_SYSCLK |
                                  RCC_CLOCKTYPE_PCLK1 |
                                  RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK) {
        Error_Handler();
    }
}

void Error_Handler(void)
{
    while (1) {
        HAL_GPIO_TogglePin(LED_FAULT_GPIO_Port, LED_FAULT_Pin);
        for (volatile uint32_t i = 0; i < 200000U; i++) {
            __NOP();
        }
    }
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
    (void)file;
    (void)line;
    Error_Handler();
}
#endif
